[en]
languageName = 'English'
weight = 1
title = 'Lingyi Meng'

[en.params]
    author = "Lingyi Meng"
    description = "Ph.D. student at Nanyang Technological University with research interests in human-robot interaction and robot learning."
    position = "Ph.D. Student at NTU"
    research_interests = "Human-Robot Interaction · Robot Learning"

[[en.menu.main]]
    name = 'About Me'
    url = '#about-me'
    weight = 1
[[en.menu.main]]
    name = 'News'
    url = '#news'
    weight = 2
[[en.menu.main]]
    name = 'Publications'
    url = '#publications'
    weight = 3
[[en.menu.main]]
    name = 'Honors and Awards'
    url = '#honors-and-awards'
    weight = 4
[[en.menu.main]]
    name = 'Education'
    url = '#education'
    weight = 5
