profilePicture = "images/profile_mly.jpeg"
favicon = "favicon.svg"
enableDarkMode = true
location = "Singapore"

# Google Analytics ID, leave empty if you don't want to use Google Analytics
googleAnalyticsID = ""

[[social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=0T4Pkv8AAAAJ"
icon = "fab fa-google-scholar"

[[social]]
name = "Email"
url = "mailto:meng0109@e.ntu.edu.sg"
icon = "fas fa-envelope"

[[social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/lingyi-meng-096788373/"
icon = "fab fa-linkedin"
